### ISSUE TITLE
Grafana role doesn't check for existing graphite install

### ISSUE THREAD

**Issue by jamengual** [bobrik/ansible-grafana#3]
Hi.

shouldn't the role check for existing installation of graphite using maybe a variable added to the role ? ( since grafana doesn't work without a working graphite install )

it seems to me that a role is useless if it doesn't actually gives the user something working, isn't that the "role" of a role ?

Maybe I'm wrong.

**Comment by bobrik** [comment]
You are not forced to have graphite installed from ansible. It is perfectly fine to have graphine installed separately without ansible. This role promises to install grafana, not graphite. Think about graphite hosted by third party, for example.

And grafana works without graphite, with influxdb for example (not in this role yet, though).
