### ISSUE TITLE
add nginx as dependency

### ISSUE THREAD

**Issue by yauh** [bobrik/ansible-grafana#5]
If you install this role it requires nginx to be available. Although you can technically install nginx manually I would like to see meta mention that nginx is required, so that this role can be easily plugged into other playbooks.

**Comment by bobrik** [comment]
I can't install nginx from ansible for whatever reason so I cannot mark nginx role as a dependency.

**Comment by yauh** [comment]
Strange, it works well for me, for example when using https://github.com/yauh/nginx_proxy

**Comment by bobrik** [comment]
Not sure what you mean, `yauh/nginx_proxy` requires nginx to be installed just like my role.

**Comment by yauh** [comment]
You are so right - I had it in another role to perform the install. nvm
